### ISSUE TITLE
Listing Empty Files Better with Just find(1)

### ISSUE THREAD

**Issue by terminalforlife** [Obony/alx-system_engineering-devops#1]
https://github.com/Obony/alx-system_engineering-devops/blob/a28eef0204ff465257f58add8633dfc70bec850b/0x02-shell_redirections/100-empty_casks#L2C1-L2C44

If you want empty files, it's better to:

```
find -type f -empty -printf '%f\n'
```

The `.` is implied, so you don't need to explicitly tell find(1) to look in the CWD. By using the `-printf` flag, you tell find(1) _how_ you would like the data to be printed. In this case, the `%f` format specifier is substituted with the filename. Specifically, this is known as the basename, hence the basename(1) tool from _coreutils_. If you're curious, the opposite is known as the dirname and there's a dirname(1) tool from _coreutils_ as well. I've also added `-type f` to tell find(1) to look only for _files_, not symlinks, block devices, FIFOs, directories, or anything else — just actual files.

This syntax is applicable for GNU find(1), BTW, so if you're on OSX or *BSD, I'm not sure it'll work for you. Non-GNU find(1) is pretty limited, unfortunately.

Lastly, remember that find(1) operates recursively by default, but `-maxdepth 1` will sort that.

Hope that helps.

**Comment by Obony** [comment]
Here's a further breakdown of the command and its options:

find: The command used to search for files and directories.
-type f: This option specifies that we are only interested in files, not directories or other types of entries.
-empty: This option filters the search to only include files that are empty, i.e., they have no content.
-printf '%f\n': With this option, we define how the output should be formatted. In this case, %f represents the filename (basename), and \n adds a newline character after each filename.
It's important to note that this command assumes you are using the GNU implementation of find, which is commonly found in Linux systems. If you're using macOS or *BSD, the command might have slightly different options or behaviors.

By specifying -maxdepth 1 after the initial find command, you can limit the search to the current directory only, instead of recursively searching subdirectories.
